# app/services/stocks.py

NSE_STOCKS = {
    "HDFC Bank":                 "HDFCBANK",
    "ICICI Bank":                "ICICIBANK",
    "State Bank of India":       "SBIN",
    "Kotak Mahindra Bank":       "KOTAKBANK",
    "Axis Bank":                 "AXISBANK",
    "Bank of Baroda":            "BANKBARODA",
    "IndusInd Bank":             "INDUSINDBK",
    "Punjab National Bank":      "PNB",
    "Canara Bank":               "CANBK",
    "Federal Bank":              "FEDERALBNK",
    "IDFC First Bank":           "IDFCFIRSTB",
    "YES Bank":                  "YESBANK",
    "RBL Bank":                  "RBLBANK",
    "Reliance Industries":       "RELIANCE",
    "Tata Consultancy Services": "TCS",
    "Infosys":                   "INFY",
    "Wipro":                     "WIPRO",
    "HCL Technologies":          "HCLTECH",
    "Larsen & Toubro":           "LT",
    "Tata Motors":               "TATAMOTORS",
    "Maruti Suzuki":             "MARUTI",
    "Bajaj Finance":             "BAJFINANCE",
    "Bajaj Finserv":             "BAJAJFINSV",
    "Sun Pharma":                "SUNPHARMA",
    "Dr Reddys":                 "DRREDDY",
    "Cipla":                     "CIPLA",
    "Asian Paints":              "ASIANPAINT",
    "ITC":                       "ITC",
    "NTPC":                      "NTPC",
    "ONGC":                      "ONGC",
    "Power Grid":                "POWERGRID",
    "Titan Company":             "TITAN",
    "UltraTech Cement":          "ULTRACEMCO",
    "Hindustan Unilever":        "HINDUNILVR",
    "Adani Ports":               "ADANIPORTS",
    "Adani Enterprises":         "ADANIENT",
    "JSW Steel":                 "JSWSTEEL",
    "Tata Steel":                "TATASTEEL",
    "Coal India":                "COALINDIA",
    "Eicher Motors":             "EICHERMOT",
}
